### ISSUE TITLE
FZF not working with Emacs 24.4

### ISSUE THREAD

**Issue by MichaelMackus** [bling/fzf.el#3]
Getting this error (when running ":fzf" after "emacs -nw"):

```bash
/home/michael/.fzf/fzf:929:in `get_input': undefined method `getc' for nil:NilClass (NoMethodError)
```

If I run "M-x fzf" in a normal emacs (gui) window, the screen just flashes for a millisecond and then gives no output.

Would be great to have fzf working here, any input would be appreciated.

**Comment by bling** [comment]
that looks like a ruby error...

double check the your emacs has the correct `PATH` set up.

**Comment by MichaelMackus** [comment]
Doh!

My bad, I fixed this by adding this to my .emacs

```lisp
'(add-to-list 'load-path "~/.fzf")
```
